import { Navbar } from '@/components/navbar'
import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { Fira_Code, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  variable: '--font-poppins',
  weight: '400',
})

const firaCode = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${firaCode.variable} antialiased`}>
        <Navbar />
        <main>{children}</main>
        <Toaster richColors />
      </body>
    </html>
  )
}
