import { Navbar } from '@/components/navbar'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { UserProvider } from '@/contexts/user-context'
import { getCurrentUser } from '@/lib/supabase/get-current-user'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import './globals.css'

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialUser = await getCurrentUser()

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <NextTopLoader color="#ff82ec" showSpinner={false} height={5} />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider initialUser={initialUser}>
            <Navbar />
            <main>{children}</main>
            <Toaster richColors />
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
